es6:  ;babel test

.PHONY: es6

test:   ;node_modules/.bin/mocha --reporter spec

test_jest: ;node_modules/.bin/jest --harmony
    
.PHONY: test

babel:  ;babel src --out-dir lib

clean:  ;rm -fdR lib
    
    
